version: '3'

services:

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '5188:5188'
    image: 1779900303085/robot-trade:client-latest

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '5656:5656'
      - '8080:8080'
    image: 1779900303085/robot-trade:server-latest

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27033:27017'
    volumes:
      - mongodb_data:/data/db

  predict:
    build:
      context: .
      dockerfile: server/pyserver/Dockerfile
    ports:
      - '8001:8001'
      - '7001:7001'
      - '6001:6001'
    image: 1779900303085/robot-trade:predict-latest

  nginx:
    image: nginx
    ports:
      - '8898:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server
      - predict
    container_name: nginx

volumes:
  mongodb_data:
