version: '3'

services:

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '5188:5188'
    image: 1779900303085/robot-trade:client-latest

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '5656:5656'
      - '8033:8033'
    image: 1779900303085/robot-trade:server-latest

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27033:27033'
    volumes:
      - mongodb_data:/data/db

  predict:
    build:
      context: .
      dockerfile: server/pyserver/Dockerfile
    ports:
      - '8801:8801'
      - '7701:7701'
      - '6601:6601'
    image: 1779900303085/robot-trade:predict-latest

volumes:
  mongodb_data:
