FROM node:18

WORKDIR /app/server

# Copy root package.json
COPY package*.json ./  

# Install root dependencies
RUN npm install --force

RUN npm install nodemon

# Install Stripe CLI
RUN curl -fsSL https://cli.stripe.com/install.sh | sh

# Copy server code
COPY server/ .
#COPY server/recData.js .

# Expose the port your app runs on
EXPOSE 5656 8033

# Define the command to run your app
CMD ["npm", "start"]




